version: '3.7'

services:
  node_app:
    build:
      context: ./node_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  react_app:
    build:
      context: ./react_app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./react_app:/app

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pd.408#>1
      MYSQL_DATABASE: pronadji_lako
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
